apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: zk-partition-r2
  namespace: default
spec:
  action: partition
  mode: all
  selector:
    namespaces:
      - default
    expressionSelectors:
      - key: statefulset.kubernetes.io/pod-name
        operator: In
        values:
          - zookeeper-2
  direction: both
  target:
    mode: all
    selector:
      namespaces:
        - default
      expressionSelectors:
        - key: statefulset.kubernetes.io/pod-name
          operator: In
          values:
          - zookeeper-0
          - zookeeper-1
  duration: "60s"
